
; PIC16F877A Configuration Bit Settings

; Assembly source line config statements

#include "p16f877a.inc"

; CONFIG
; __config 0xFF32
 __CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

 
	ORG	0
	GOTO	INICIO
INICIO
	BSF	STATUS,RP0
	CLRF	TRISD; SALIDA
	BSF	TRISA,0; RA0 ENTRADA
	CLRF	TRISC; SALIDA
	BSF	ADCON1,3
	BSF	ADCON1,2
	BSF	ADCON1,1
	BCF	ADCON1,0; 1110 -> RA0 AN0 = ANALOGO
	BSF	ADCON1,6; FOSC/64
	BCF	ADCON1,7; JUSTIFICACION IZQ
	BCF	STATUS,RP0
	BSF	ADCON0,7
	BCF	ADCON0,6; FOSC/64
	BCF	ADCON0,5
	BCF	ADCON0,4
	BCF	ADCON0,3; CANAL AN0
	BSF	ADCON0,0; ADC ON
START
	BSF	ADCON0,2; GO/DONE -> 1
ADC	BTFSC	ADCON0,2
	GOTO	ADC
	MOVF	ADRESH,W
	MOVWF	PORTD
	BSF	STATUS,RP0
	MOVF	ADRESL,W
	BCF	STATUS,RP0
	MOVWF	PORTC
	CALL	Retardo_20ms 
	CALL	Retardo_20ms 
	CALL	Retardo_20ms 
	CALL	Retardo_20ms 
	CALL	Retardo_20ms 
	GOTO	START
	
include "Retardo.inc"	
	END