
; PIC16F877A Configuration Bit Settings

; Assembly source line config statements

#include "p16f877a.inc"

; CONFIG
; __config 0xFF32
 __CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

 
	ORG	0
	GOTO	INICIO
INICIO
	BSF	STATUS,RP0
	MOVLW	.31; BAUDIOS 9600
	MOVWF	SPBRG
	BCF	TXSTA,4; ASINCRONO
	BCF	TXSTA,2; LOW SPEED
	BCF	TXSTA,6; 8 BITS
	BSF	TXSTA,5; HABILITA TX
	BSF	PIE1,RCIE; HABILITA INT RX
	CLRF	TRISD; SALIDA
	BCF	STATUS,RP0
	BSF	RCSTA,7; RX Y TX
	BSF	RCSTA,4; HABILITA RX
	BCF	RCSTA,6; 8 BITS
	BCF	PIR1,RCIF; LIMPIAMOS FLAG RX
START
	BTFSS	PIR1,RCIF
	GOTO	START
	MOVF	RCREG,W; RCREG -> W
	XORLW	'W'; W XOR WREG -> 0 - STATUS,Z Z=1 
	BTFSS	STATUS,Z;             OPERACION 0
	GOTO	START
	MOVLW	'A'
	MOVWF	TXREG
	BCF	PIR1,RCIF; APAGO INT RX
	CALL    Retardo_20ms
	GOTO	START
	
	
include "Retardo.inc"	
	END
	
	
	
	
	
	
	