
; PIC16F877A Configuration Bit Settings

; Assembly source line config statements

#include "p16f877a.inc"

; CONFIG
; __config 0xFF32
 __CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF

 
	ORG	0
	GOTO	INICIO
	ORG	0X0020
INICIO
	CALL	LCD_INIT
	MOVLW	.1
	CALL	LCD_LINEA1
	MOVLW	'H'
	CALL	LCD_CARACTER
	MOVLW	'O'
	CALL	LCD_CARACTER
	MOVLW	'L'
	CALL	LCD_CARACTER
	MOVLW	'A'
	CALL	LCD_CARACTER
	MOVLW	.5
	CALL	LCD_LINEA2
	MOVLW	'W'
	CALL	LCD_CARACTER
	MOVLW	'E'
	CALL	LCD_CARACTER
	MOVLW	'L'
	CALL	LCD_CARACTER
	MOVLW	'S'
	CALL	LCD_CARACTER
START
	GOTO	START
#INCLUDE <LCD_4bits.inc>
	END


