#include "p16f877a.inc"

; CONFIG
; __config 0xFF32
 __CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF
 
 NUMERO EQU D'6'
 
    ORG	0
INICIO
    BSF	    STATUS,RP0
    BCF	    STATUS,RP1
    CLRF    TRISD
    MOVLW   B'11111111'
    MOVWF   TRISB
    BCF	    STATUS,RP0
    CLRF    PORTD
START
    ; SI LA RESTA = POSITIVA, C=1 Z=0  PORTB - NUMERO > 0
    ; SI LA RESTA = CERO    , C=1 Z=1  PORTB - NUMERO = 0
    ; SI LA RESTA = NEGATIVA, C=0 Z=0  PORTB - NUMERO < 0
    MOVLW   NUMERO      ;W = NUMERO
    SUBWF   PORTB,W;	;PORTB - W(NUMERO) = W 
    MOVLW   B'10000000' ;POSITIVO 
    BTFSC   STATUS,Z
    MOVLW   B'11111111' ;IGUALES
    BTFSS   STATUS,C
    MOVLW   B'00000001' ;NEGATIVO
    MOVWF   PORTD
    GOTO    START
    END